.de dname
. nop MariaDB/MySQL
..
./"
./"
.TH schemagen 1 "28 October 2021" "Version 0.5"
./"
./"
.SH NAME
schemagen \- Schema Script Generator
./"
./"
.SH SYNOPSIS
.BR schemagen [
.IR options ]
./"
./"
.SH DESCRIPTION
This utility generates stored procedures code from an indicated
.dname
table.  The procedures are generated to conform to the recommended Schema
Framework conventions.
./"
./"
.SH OPTIONS
./"
./"
.SS Connection Options
.TP
.BR \-H ", " \-\-host
Address of 
.dname
database host.  This can be in dotted-decimal format or a host name.
.TP
.BR \-u ", " \-\-user
Account username for the
.dname
host. This is optional if the
.dname
name is the same as the OS username.
.TP
.BR \-p ", " \-\-password
Account password for the
.dname
host.  This is optional if the
.dname
account has a blank password.
./"
./"
.SS Domain Options
.TP
.BR \-d ", " \-\-database
name of
.dname
database that hosts the tables and procedures.
.TP
.BR \-t ", " \-\-table
name of a table in the
.dname
database on the host.  Although it generates no
error, specifying a table without a database will not work.
./"
./"
.SS Output Types
.TP
.BI \-h ", " \-\-help
Quick help
.TP
.BI \-a ", " \-\-args
Writes option values in a format that serves as a
.I schemagen.cnf
configuration file.  With a configuration file in the local directory, the values
contained therein will be used as default option values.  This option can also be
used to view the current option values.
.TP
.BR \-l ", " \-\-list
List the specified items in the existing domain (as set by the connection options).
Allowed values are
.IR databases ", " tables ", " procedures ", and " fields.
.I databases
works with any connection, but 
.IR tables " and " procedures
must have set the
.BR \-\-database " option."
The
.I fields
option lists the fields of a table and only works if the
.BR \-\-database " and " \-\-table
options have been set.
.\"
.TP
.BR \-s ", " \-\-script
Generate one or more
.dname
stored procedure declarations based on the
.BR \-\-database " and " \-\-table
options.  Allowed values are
.IR all ", " list ", " add ", " read ", " update ", and " delete ,
and the stored procedure script will be generated that corresponds
to the
.B \-\-script
option value.
./"
./"
.SS Output Formatting
.TP
.BR \-I " and " \-\-indent-chars
Number of character positions for each tab stop
.TP
.BR \-i " and " \-\-items-per-line
Maximum number of items (parameters, select fields) per line in
stored procedure code.  The default value,
.IR -1 ,
indicates to limit to items per line, which may be further restricted
by
.B \-\-max-chars
per line.  Items are not broken, so a long item with more characters
than
.B \-\-max-chars
will print out past the right limit.

The default
.RI ( -1 )
is to print as many items per line as fit, but for
procedures intended to be templates, using
.B \-\-max-chars=1
may make it easier to search for, add, or remove items from the template.

.TP
.BR \-m " and " \-\-max-chars
Maximum number of characters per line.

.SH NOTES
.SS Using schemagen.cnf
Putting commonly-used connection values into a configuration file
can make it easier to user the
.B schemagen
utility.  Using the
.B \-\-args
option may make it easier to generate this file.

Create the
.B schemagen.cnf
file with confirmed values by using the connection options on the same
call as the
.B \-\-args
option.  See EXAMPLES below.


./"
./"
.ds aang_nd \fBschemagen -H \fI192.168.0.20\fB -u \fIAang\fB -p\fIkatara\fR
.ds aang \fBschemagen -H \fI192.168.0.20\fB -u \fIAang\fB -p\fIkatara \fB-d \fIAirNation\fR
.SH EXAMPLES

See list of a host's databases
.RS
\*[aang_nd] \fB-l \fIdatabases\fR
.RE

See list of table in a database
.RS
\*[aang] \fB-l \fItables\fR
.RE

Generate Procedures based on table Avatars
.RS
\*[aang] \fB-t\fI Avatars \fB-s \fIall\fR
.RE

Generate Specific Procedure
.RS
\*[aang] \fB-t\fI Avatars \fB-s \fIupdate\fR
.RE

Adjust output to create template with one-per-line parameters
.RS
\*[aang] \fB-t\fI Avatars \fB-s \fIall \fB-i \fI1\fR
.RE

Create a schemagen.cnf file
.RS
\*[aang] \fB--args\fR > schemagen.cnf
.RE


./"
./"
.SH SEE ALSO
.TP
.BR schema.fcgi "(7), " schemaserver ", " schemafw
